language: node_js

stages:
  - test
  - build

jobs:
  include:
    - name: Test with Node.js lts/*
      stage: test
      node_js: "lts/*"
      script:
        - npm test
    - name: Build with Node.js lts/*
      stage: build
      node_js: "lts/*"
      script:
        - npm run build
    - name: Build with Node.js stable
      stage: build
      node_js: "stable"
      script:
        - npm run build
